language: node_js
node_js:
  - "8"
deploy:
  provider: heroku
  api_key:
    secure: NxoEzWdp1WQy1LN9pTTIkom7cDtu62+18Ot5/i3qkaX41BT2J3GxZcJWPFQIwVFtZc2q8Wz0X7COm76BDQouEV/ddbvh7aiqrDZCNTBn4Hpx/q6UwYwSfsg43xuMdZaVMkJVbqU/8vsLuVhUIqi8c1nglE3AkbDLqbhI2NMt8xX4x4SDWwyAPIM0kQG63g5WRY1pgfVcw0IbgcKThh2U/kyEM7RCx6SxKiGNvSwA1X3OU11APGrS6v7DRCpJD8sQubAWJgY1/xruFaaRvuMdwggh1i6hxdv4SjbLs15HWzTi8jHDogP+h/r0qi/q32kBknVOGcN2+VlwIddo9DG24oUxHvnN5xJIJt73p4o0zL464lU8XEZigJKcLb/sDjsxGC/V667pG6W/kRPEi9OjtMOM3PuktKrRkLPJ79bK7f377ZFU9d7ye8TH6OktVrn1qDUKpHunrCW5LimTDqHWzWjsjXvX4Qit61lKMD9T6tpxI/2jfY9W0uucqK5thkyK6Z0w4seVZ77orf4f8XRIHTicoQJ/hoDHygzY2QNeT9nCQrSEwJUWQWAcYLzzYihM5qm9Ltdy2dVLqDPVlyJVxH5BtXzuqKeoMOAI3I8G0N/X1VCQOFoh/xV/IqljCJ7xkDMrSzUV01K50a6vH4oFsAk2EkH51zMVH/3NUlc/P7M=
  app: cwb-graphql-gateway
